[package]
name = "frd_lisp"
version = "0.1.0"
authors = ["Fran Guijarro <franleplant@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "*"

[dependencies]
lalrpop-util = "*"
regex = "*"
log = "*"
env_logger = "*"
